In [1]:
import numpy as np
import pandas as pd

In [2]:
big_music = pd.read_csv("tcc_ceds_music.csv")
big_music.head()

,Unnamed: 0,artist_name,track_name,release_date,genre,lyrics,len,dating,violence,world/life,...,sadness,feelings,danceability,loudness,acousticness,instrumentalness,valence,energy,topic,age
0,0,mukesh,mohabbat bhi jhoothi,1950,pop,hold time feel break feel untrue convince spea...,95,0.000598,0.063746,0.000598,...,0.380299,0.117175,0.357739,0.454119,0.997992,0.901822,0.339448,0.137110,sadness,1.0
1,4,frankie laine,i believe,1950,pop,believe drop rain fall grow believe darkest ni...,51,0.035537,0.096777,0.443435,...,0.001284,0.001284,0.331745,0.647540,0.954819,0.000002,0.325021,0.263240,world/life,1.0
2,6,johnnie ray,cry,1950,pop,sweetheart send letter goodbye secret feel bet...,24,0.002770,0.002770,0.002770,...,0.002770,0.225422,0.456298,0.585288,0.840361,0.000000,0.351814,0.139112,music,1.0
3,10,pérez prado,patricia,1950,pop,kiss lips want stroll charm mambo chacha merin...,54,0.048249,0.001548,0.001548,...,0.225889,0.001548,0.686992,0.744404,0.083935,0.199393,0.775350,0.743736,romantic,1.0
4,12,giorgos papadopoulos,apopse eida oneiro,1950,pop,till darling till matter know till dream live ...,48,0.001350,0.001350,0.417772,...,0.068800,0.001350,0.291671,0.646489,0.975904,0.000246,0.597073,0.394375,romantic,1.0

In [3]:
smaller_music = big_music.sample(4000, random_state=1).reset_index(drop=True)
smaller_music.head()

,Unnamed: 0,artist_name,track_name,release_date,genre,lyrics,len,dating,violence,world/life,...,sadness,feelings,danceability,loudness,acousticness,instrumentalness,valence,energy,topic,age
0,58888,glenn miller,the little man who wasn't there,1991,jazz,beneke whistle miller hello texas whatcha whis...,59,0.001316,0.059445,0.001316,...,0.373436,0.001316,0.728149,0.638028,0.871486,0.037551,0.570280,0.422404,sadness,0.414286
1,76652,misfits,american psycho,1997,rock,inside wall street mind psycho lurk line cocai...,95,0.001144,0.704463,0.001144,...,0.057953,0.001144,0.477959,0.781376,0.000479,0.000581,0.061212,0.994995,violence,0.328571
2,14001,elliott smith,somebody that i used to know,2000,pop,tender feel hard heart scar home somebody know...,33,0.001595,0.001595,0.056699,...,0.334759,0.176986,0.571104,0.535113,0.403614,0.000001,0.781533,0.368349,sadness,0.285714
3,20370,june carter cash,juke box blues,1952,country,walk honkey tonkey drop nickle juke hear play ...,75,0.001170,0.038642,0.001170,...,0.110659,0.001170,0.858118,0.689101,0.866466,0.000683,0.846455,0.356336,music,0.971429
4,56714,"emerson, lake & palmer","karn evil 9 1st impression, pt. 1",1973,jazz,cold morning hear warn bear power hour spare s...,95,0.000892,0.400653,0.025214,...,0.252190,0.000892,0.399978,0.624003,0.179718,0.004352,0.684666,0.544530,violence,0.671429

In [4]:
print(smaller_music.shape)
print(big_music.shape)

(4000, 31)
(28372, 31)

In [5]:
display(smaller_music['genre'].value_counts()/len(smaller_music))
display(big_music['genre'].value_counts()/len(big_music))

pop        0.25150
country    0.19450
blues      0.16400
rock       0.13975
jazz       0.13500
reggae     0.08825
hip hop    0.02700
Name: genre, dtype: float64

pop        0.248202
country    0.191915
blues      0.162273
rock       0.142182
jazz       0.135521
reggae     0.088045
hip hop    0.031862
Name: genre, dtype: float64

In [6]:
not_hot100=smaller_music[['track_name', 'artist_name']].rename(columns = ({"track_name": "song_name", "artist_name":"song_artist"}))
print(not_hot100.shape)
display(not_hot100.head())

(4000, 2)

                           song_name             song_artist
0    the little man who wasn't there            glenn miller
1                    american psycho                 misfits
2       somebody that i used to know           elliott smith
3                     juke box blues        june carter cash
4  karn evil 9 1st impression, pt. 1  emerson, lake & palmer

In [7]:
hot100=pd.read_csv("hot100.csv")

In [8]:
hot100.head()

           song_name                          song_artist
0          Anti-Hero                         Taylor Swift
1      Lavender Haze                         Taylor Swift
2             Maroon                         Taylor Swift
3  Snow On The Beach  Taylor Swift Featuring Lana Del Rey
4      Midnight Rain                         Taylor Swift

In [9]:
hot100 = hot100.applymap(lambda s:s.lower() if type(s) == str else s)
hot100.head()

           song_name                          song_artist
0          anti-hero                         taylor swift
1      lavender haze                         taylor swift
2             maroon                         taylor swift
3  snow on the beach  taylor swift featuring lana del rey
4      midnight rain                         taylor swift

In [10]:
repeated = hot100.merge(not_hot100.reset_index())['index'].tolist()
repeated

[]

In [11]:
hot100.loc[len(hot100.index)] = ['american psycho', 'misfits']

In [12]:
repeated_ex = hot100.merge(not_hot100.reset_index())['index'].tolist()
repeated_ex

[1]

In [ ]:
not_hot100.to_csv("")